### ISSUE TITLE
API connection failed

### ISSUE THREAD

**Issue by jussirantala** [manhinhang/ib-gateway-docker#60]
Hey,

I'm running the latest image from Docker Hub but I get this error. Isn't this supposed to run IBG inside the container?

`dev-ib-gateway  | [2022-10-27 11:01:00,943]ERROR:API connection failed: ConnectionRefusedError(111, "Connect call failed ('127.0.0.1', 4001)")`
`dev-ib-gateway  | [2022-10-27 11:01:00,944]ERROR:Make sure API port on TWS/IBG is open`

**Comment by manhinhang** [comment]
I tested that latest image is fine , I think you may need set larger timeout value.
https://github.com/manhinhang/ib-gateway-docker#other-environment-variable

**Comment by gooner22** [comment]
from the IB docs:
4001 is the default port for live IB Gateway sessions
4002 is the default port for paper IB Gateway sessions

looks like current setup works only for live accounts.

@jussirantala 
solved the problem by changing Watchdog port to 4002

**Comment by Neovet** [comment]
I'm getting same error on my end:

```ib-gateway  | [2022-12-08 04:48:39,349]INFO:start ib gateway...
ib-gateway  | [2022-12-08 04:48:39,350]INFO:---ib gateway info---
ib-gateway  | [2022-12-08 04:48:39,350]INFO:ib gateway version:1012
ib-gateway  | [2022-12-08 04:48:39,350]INFO:ib gateway path:/root/Jts/ibgateway/1012
ib-gateway  | [2022-12-08 04:48:39,350]INFO:-------------------
ib-gateway  | [2022-12-08 04:48:39,351]INFO:Starting
ib-gateway  | [2022-12-08 04:48:39,351]INFO:WatchDog Starting...
ib-gateway  | [2022-12-08 04:48:39,351]INFO:Starting
ib-gateway  | [2022-12-08 04:49:09,374]INFO:Connecting to 127.0.0.1:4001 with clientId 1...
ib-gateway  | [2022-12-08 04:49:09,375]INFO:Disconnecting
ib-gateway  | [2022-12-08 04:49:09,375]ERROR:API connection failed: ConnectionRefusedError(111, "Connect call failed ('127.0.0.1', 4001)")
ib-gateway  | [2022-12-08 04:49:09,375]ERROR:Make sure API port on TWS/IBG is open
ib-gateway  | [2022-12-08 04:49:09,376]INFO:Terminating
ib-gateway  | [2022-12-08 04:49:09,721]INFO:WatchDog Stopped!
```

Tried to use high-enough timeouts, still rejection comes much earlier.
The only guess is that may not configure ib-gateway to accept incoming connections.

**Comment by gooner22** [comment]
maybe it can help someone,
I had the same frustrating issue when run on Apple M1 in docker cluster.
my issues disappeared when I moved to cloud environment & linux arm64 arch,
not sure what was the original reason for this but it took tones of time to figure out..
very frustrating. 
good luck to next gens
