### ISSUE TITLE
Modifying gateway API settings?

### ISSUE THREAD

**Issue by mblanco4x4** [manhinhang/ib-gateway-docker#62]
Hi, seems to be working great so far. How can I make a change to the gateway API settings in the GUI interface? There's a setting called "Send market data in lots for US stocks for dual-mode API clients" - I need this to be CHECKED. By default it is unchecked.

Forgive me if this is a silly question, I'm a novice at these things.

Thanks

**Comment by manhinhang** [comment]
I think it can config by [config.ini](https://github.com/manhinhang/ib-gateway-docker/blob/develop/ibc/config.ini) file.

**Comment by mblanco4x4** [comment]
> I think it can config by [config.ini](https://github.com/manhinhang/ib-gateway-docker/blob/develop/ibc/config.ini) file.

Ahh OK I see it.

"SendMarketDataInLotsForUSstocks="

Thank you!
