### ISSUE TITLE
[Question] Why install the ib_insync inside the docker

### ISSUE THREAD

**Issue by dnoredu** [manhinhang/ib-gateway-docker#70]
I'm a doker newbie, and curious why the ib_insync is installed with this docker image? And in the ib_insync [example](https://github.com/manhinhang/ib-gateway-docker/blob/develop/examples/ib_insync), the ib_insync has to install on the host again.

**Comment by manhinhang** [comment]
> I'm a doker newbie, and curious why the ib_insync is installed with this docker image? And in the ib_insync [example](https://github.com/manhinhang/ib-gateway-docker/blob/develop/examples/ib_insync), the ib_insync has to install on the host again.

I'm planning remove ib_insync in host. The original reason just give choice that user allow to connect ib gateway inside or outside of host
