### ISSUE TITLE
Paper trading is broken

### ISSUE THREAD

**Issue by rl3250** [manhinhang/ib-gateway-docker#78]
it seems like the gateway connects live trading fine, but paper trading is broken, the 2FA push notification is never delivered

**Comment by manhinhang** [comment]
> it seems like the gateway connects live trading fine, but paper trading is broken, the 2FA push notification is never delivered

I think paper trade account should be fine. My automatic test is also using paper trade account and result is fine.
https://github.com/manhinhang/ib-gateway-docker/actions/runs/8674090878/job/23786072425

**Comment by rl3250** [comment]
I see... probably something is broken for my accounts, the error message is exactly the same as in #71 so I think I'm not alone

**Comment by manhinhang** [comment]
> I see... probably something is broken for my accounts, the error message is exactly the same as in #71 so I think I'm not alone.
> 
> For context, I'm using the same account for live/paper trading, and I just can't receive the 2FA notification for paper account.

My paper trade account is not required 2FA, I think your issue related account settings.
